# Generated by Django 2.2.6 on 2020-01-30 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genero', '0002_auto_20200123_1220'),
        ('municipio', '0001_initial'),
        ('perfiljuridico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juridicos',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=154, null=True)),
                ('mail', models.CharField(blank=True, max_length=50, null=True)),
                ('fijo', models.CharField(blank=True, max_length=15, null=True)),
                ('cedula', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tarjetaprofesional', models.CharField(blank=True, db_column='tarjetaProfesional', max_length=30, null=True)),
                ('fecha_s', models.DateField(blank=True, null=True)),
                ('login', models.CharField(max_length=256)),
                ('ciudad', models.ForeignKey(blank=True, db_column='ciudad', null=True, on_delete=django.db.models.deletion.PROTECT, to='municipio.Municipio')),
                ('genero', models.ForeignKey(blank=True, db_column='genero', null=True, on_delete=django.db.models.deletion.PROTECT, to='genero.Genero')),
                ('perfil', models.ForeignKey(blank=True, db_column='perfil', null=True, on_delete=django.db.models.deletion.PROTECT, to='perfiljuridico.Perfiljuridico')),
            ],
            options={
                'db_table': 'juridicos',
                'managed': True,
            },
        ),
    ]
