# Generated by Django 2.2.6 on 2020-02-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desicion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desicion',
            options={'managed': False, 'verbose_name': 'Desicion', 'verbose_name_plural': 'Desiciones'},
        ),
    ]
